### ISSUE TITLE
[Support Request] parabolic control problems with control only dependent on time

### ISSUE THREAD

**Issue by irenier** [sblauth/cashocs#184]
I'm trying to solve a problem as follows.

$$
\min_u \frac{1}{2}\int_0^T \int_\Omega \left(y - y_d\right)^2 \ \mathrm{d}x\mathrm{d}t + \frac{\lambda}{2} \int_{0}^{T} \int_\Omega u^2 \ \mathrm{d}x\mathrm{d}t
$$

subject to

$$
\begin{alignat}{2}
    y_t - \Delta y & = u(t),  \quad      &  & \text{in}\ (0,T) \times \Omega          \\
    y                & = 0, \quad          &  & \text{on}\ [0,T] \times \partial \Omega \\
    y(0,x)           & = y_0(x) = 0, \quad &  & \text{in} \ \Omega
\end{alignat}
$$

where the control $u$ is **only** dependent on temporal variable $t$ and independent of spatial variable $x$.

I thought just slight modification on the following code would work.
https://github.com/sblauth/cashocs/blob/e0296106cde6c5e420c56b0e7e074f552de895d6/demos/documented/optimal_control/heat_equation/demo_heat_equation.py#L134
But unfortunately it didn't. So how can I make it work?

**Comment by sblauth** [comment]
Hi,

so if I understand you correctly, for your problem, the control variable is given by $u \colon [0,T] \to \mathbb{R}$, so that $u(t) \in \mathbb{R}$ for all $t\in [0,T]$? If that is the case, then you can really just modify the above line and use
```
R = FunctionSpace(mesh, "R", 0)
controls = [Function(R) for i in range(len(t_array))]
```
instead. The space `R` is a space of constant (in space) functions, so that its degree is $0$. As a side note, this space is also what FEniCS uses internally when using `fenics.Constant`.

I hope that this helps you solve your problem - if not, you can elaborate your issue here.

**Comment by irenier** [comment]
Thanks, @sblauth. Your solution is exactly what I was looking for.
